### ISSUE TITLE
Maximize the lockscreen

### ISSUE THREAD

**Issue by ghost** [wasdennnoch/LockMod#1]
Hi, is there a way to make the pattern (almost) full screen, leaving out space for text and the emergency button? I have been trying to figure this out since a long time, but I think you might have a better idea. Thanks!

**Comment by wasdennnoch** [comment]
To fill the whole screen, the pattern would have to be stretched; is this really what you want? Wouldn't it look a bit weird? Or do you only want to hide everything except for the pattern?

**Comment by ghost** [comment]
Well, I think distorted is okay. I'm not asking for the pattern
specifically, but because I'm the developer for Knock Code and I'm trying
to get it to be full screen, and I think your research into the pattern
realm will help me. Hope you don't mind :)

**Comment by wasdennnoch** [comment]
Oh, I see your problem: Your KnockCodeUnlockView has the same size like any other unlock method because it simply replaces them.
Currently I'm investigating how the keyguard works too. I think you'll have to change the size of the view parents because they are setting the unlock method container size. 
Have a look at those layout files (source of my specific rom, but they should be unmodified): https://github.com/TeamBliss-LP/android_frameworks_base/blob/lp5.1/packages/Keyguard/res/layout/keyguard_simple_host_view.xml and https://github.com/TeamBliss-LP/android_frameworks_base/blob/lp5.1/packages/Keyguard/res/layout-port/keyguard_host_view.xml

**Comment by wasdennnoch** [comment]
I also noticed that you are initializing a `Paint` object in the `onDraw` method of the `LineView` class - you really shouldn't do that, even if it's only once, it causes the first frame to take much longer to be drawn which causes everything to lag.

**Comment by ghost** [comment]
Hi, thanks for the answer to my question and the feedback, I will fix it soon. About that link, I had figured that the first element _com.android.keyguard.KeyguardHostView_ has height match_parent, I should look for its parent to change the height, right? That's what I've been unable to find, really.

**Comment by wasdennnoch** [comment]
From what I've unserstood so far the `KeyguardHostView` fills the whole screen; the `KeyguardSecurityContainer` might be the "main" lock screen, and the `KeyguardSecurityViewFlipper` could be the container for the unlock screen. I had no time yet to look at it, but I will (hopefully) do that today and will notify you of new discoveries.

**Comment by ghost** [comment]
Okay, so I tried replacing this resource in the dimens.xml by my screen height in dp, it did not work.
`<dimen name="keyguard_security_max_height">450dp</dimen>`

**Comment by ghost** [comment]
`<dimen name="keyguard_security_height">400dp</dimen>` replacing this by the screen height, already calculated for my device, works. I was wondering if there was a way to dynamically replace this by the screen height? Thank you so much for your time.

**Comment by ghost** [comment]
Apparently setting the replacement to be outrageously large does the trick. Thank you for your help!

**Comment by wasdennnoch** [comment]
I'm currently experimenting with the layouts and views too, nice to hear that your problem is solved!
